function output = indef_integral(input)
    output = zeros(1,len(input));
    inputs = input.y;
    fs = input.fs;
    for i = 2:len(input)
        output(i) = output(i-1)+inputs(i)/fs;
    end
    output = output - mean(output);
    output = ao(plist(...
        'yvals',output,...
        'yunits',input.yunits*input.xunits,...
        'fs',input.fs,...
        't0',input.t0,...
        'toffset',input.toffset));
end